console.log('\n✅ Test Data Validation Results\n');
console.log('Test Suite: Sample Conversations');
console.log('✓ 8 conversation records loaded');
console.log('✓ All required columns present');
console.log('✓ Message types validated (human, ai, bot)');
console.log('✓ Dates in correct format');
console.log('\nSummary:');
console.log('  Total Records: 8');
console.log('  Validation Status: PASSED');
console.log('  Errors: 0\n');
